### ISSUE TITLE
no symbol named "*STANDARD-OPTIMIZE-SETTINGS*" in "CL-PPCRE"

### ISSUE THREAD

**Issue by whatacold** [edicl/cl-unicode#20]
Hi,

`(ql:quickload :cl-unicode)` results in the error as in the title, the implementation I use is sbcl:

    $ sbcl --version
    SBCL 1.4.2-1.fc27

**Comment by stassats** [comment]
Can't reproduce.

**Comment by whatacold** [comment]
With help of `(ql:where-is-system "cl-ppcre")`, I find that it was because I load a older cl-ppcre from PCL, which lacks this symbol.

sorry.
