### ISSUE TITLE
Quicklisp symbol-call error.

### ISSUE THREAD

**Issue by jan-lastovicka** [edicl/cl-unicode#21]
The error below occurs in LispWorks Personal Edition (version 6.1.1) running on macOs Mojave (version 10.14.1) while loading via quickload.

(ql:quickload "cl-unicode")

Error: Error while trying to load definition for system cl-unicode from pathname .../quicklisp/dists/quicklisp/software/cl-unicode-20180328-git/cl-unicode.asd:
          (SYMBOL-CALL :CL-UNICODE (QUOTE #:CREATE-SOURCE-FILES)) does not match (ASDF::O ASDF::C).

**Comment by stassats** [comment]
I guess it doesn't work with asdf 2 since 2c8342824d5495e4039c25caf22fb63ec5ce6779
