### ISSUE TITLE
char-info:case-folding-mapping type is nil - ccl fails

### ISSUE THREAD

**Issue by bahmanm** [edicl/cl-unicode#24]
when trying to `(ql:quickload "cl-unicode")` or `(asdf:load-system :cl-unicode)`, clozure cl fails with

```
The value NIL, derived from the initform NIL, can not be used to set the value of 
the slot CL-UNICODE::CASE-FOLDING-MAPPING in #<CL-UNICODE::CHAR-INFO #x30200268A09D>, 
because it is not of type NIL.
   [Condition of type CCL::BAD-SLOT-TYPE-FROM-INITFORM]
```

the error is coming from [`char-info:case-folding-mapping`](https://github.com/edicl/cl-unicode/blob/54bdf2c905a4c1eefa4eb9bce86c3a136b6ea177/build/char-info.lisp#L140) which has the type `nil`. 

the documentation reads
> The case folding mapping of the character \(as a list of \(status, code point)) if explicitly specified

so perhaps `(or list null)` is a better option than `nil`? what do you think?

**Comment by stassats** [comment]
nil is not even an option. Should either just remove it or make it `list`. (And null is already a list.)

**Comment by bahmanm** [comment]
yes..makes sense. i'm testing out `list` against sbcl, ccl and ecl. should have a pr out shortly.

**Comment by bahmanm** [comment]
thanks for the quick fix.
